### ISSUE TITLE
Clarify a "multi-level wildcard"

### ISSUE THREAD

**Issue by rgrinberg** [zotonic/router#1]
From the readme:

> There is one multi-level wildcard '#' which matches all elements on the path.

What does that mean exactly? I assume it means the rest of the path but would really like an example like the other elements.

**Comment by arjan** [comment]
Good question!
@mmzeeman is it analogous to MQTT-style wildcards? (http://www.eclipse.org/paho/files/mqttdoc/Cclient/wildcard.html)

**Comment by mmzeeman** [comment]
Yes, Arjan is right. It is analogous to MQTT wildcards.

**Comment by rgrinberg** [comment]
Thank you! I'm not familiar with mqtt but the linked page was enough for me to understand. I'd still recommend clarifying this in the readme however.

**Comment by mmzeeman** [comment]
Thanks for the feedback. I just added some lines to the readme .
